# Compiles every .comp file in a shader directory to SPIR-V with the offline
# glslangValidator, then bakes each binary into a checked-in C++ header
# ({name}.spv.h) next to the source. Regular GDExtension builds therefore have
# no glslang dependency — this script only runs when a shader changes.
#
# Usage:
#   powershell -File Source/TreeGen/SlowTree/tools/build_slowtree_shaders.ps1 [ShaderDir] [GlslangExe]
# ShaderDir 缺省为脚本旁的 ..\shaders(无需指定仓库根 cwd)。
param(
    [string]$ShaderDir = "",
    [string]$GlslangExe = ""
)

$ErrorActionPreference = "Stop"

function Find-Glslang {
    param([string]$Explicit)
    if ($Explicit -ne "" -and (Test-Path $Explicit)) { return $Explicit }
    if ($env:VULKAN_SDK -ne $null -and (Test-Path "$env:VULKAN_SDK\Bin\glslangValidator.exe")) {
        return "$env:VULKAN_SDK\Bin\glslangValidator.exe"
    }
    $candidates = @(
        "D:\WorkSpace\VulkanSDK\Bin\glslangValidator.exe",
        "C:\VulkanSDK\Bin\glslangValidator.exe"
    )
    foreach ($c in $candidates) { if (Test-Path $c) { return $c } }
    $cmd = Get-Command glslangValidator -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    throw "glslangValidator not found. Install the Vulkan SDK or pass -GlslangExe."
}

function ConvertTo-HeaderName {
    param([string]$BaseName)
    ($BaseName.ToUpperInvariant() -replace '[^A-Z0-9]', '_') + "_SPV"
}

$Glslang = Find-Glslang -Explicit $GlslangExe
if ($ShaderDir -eq "") {
    $ShaderDir = Join-Path $PSScriptRoot "..\shaders"
}
if ([System.IO.Path]::IsPathRooted($ShaderDir)) {
    $ShaderRoot = $ShaderDir
} else {
    $ShaderRoot = Join-Path (Get-Location) $ShaderDir
}
if (-not (Test-Path $ShaderRoot)) { throw "Shader dir not found: $ShaderRoot" }

Write-Host "glslang: $Glslang"
Write-Host "shaders: $ShaderRoot"

$TempSpv = Join-Path $env:TEMP "slowtree_shader.spv"
Get-ChildItem -Path $ShaderRoot -Filter *.comp | ForEach-Object {
    $Src = $_.FullName
    $Header = Join-Path $_.DirectoryName ($_.BaseName + ".spv.h")
    $Sym = ConvertTo-HeaderName -BaseName $_.BaseName

    & $Glslang -V -S comp $Src -o $TempSpv
    if ($LASTEXITCODE -ne 0) { throw "glslang failed: $Src" }

    $Bytes = [System.IO.File]::ReadAllBytes($TempSpv)
    if (($Bytes.Length % 4) -ne 0) { throw "SPIR-V size not word-aligned: $Src" }
    $WordCount = $Bytes.Length / 4
    $Words = New-Object uint32[] $WordCount
    [System.Buffer]::BlockCopy($Bytes, 0, $Words, 0, $Bytes.Length)

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("// GENERATED by Source/TreeGen/SlowTree/tools/build_slowtree_shaders.ps1 from $($_.Name) — do not edit.")
    [void]$sb.AppendLine("#pragma once")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("#include <cstdint>")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("static const uint32_t ${Sym}[] = {")
    for ($i = 0; $i -lt $WordCount; $i += 8) {
        $line = ($Words[$i..([Math]::Min($i + 7, $WordCount - 1))] | ForEach-Object { "0x{0:X8}" -f $_ }) -join ", "
        [void]$sb.AppendLine("    $line,")
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine("static constexpr uint32_t ${Sym}_WORDS = $WordCount;")
    [void]$sb.AppendLine("")

    [System.IO.File]::WriteAllText($Header, $sb.ToString())
    Write-Host "  $($_.Name) -> $($_.BaseName).spv.h ($WordCount words)"
}
Write-Host "done."
