#!/usr/bin/env python3
"""Extracts the Paul Bourke marching-cubes tables (edgeTable, triTable) from the
Unity procedural-rock reference shader and emits them as a C++ header.

Source: Reference/Unity-Procedural-Rock-Generation/Assets/Code/Triangulation.compute
(reference tables: http://paulbourke.net/geometry/polygonise/)

Run from the repo root with:  uv run python Source/RockGen/tools/convert_mc_tables.py
The header is checked in, so this only needs re-running if the tables ever change.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "Reference/Unity-Procedural-Rock-Generation/Assets/Code/Triangulation.compute"
OUTPUT = ROOT / "Source/RockGen/RockMarchingCubesTables.h"


def extract_block(text: str, decl: str) -> str:
    start = text.index(decl)
    start = text.index("=", start) + 1
    start = text.index("{", start) + 1
    end = text.index("};", start)
    return text[start:end]


def parse_ints(body: str) -> list[int]:
    values = []
    for token in re.findall(r"-?0x[0-9a-fA-F]+|-?\d+", body):
        values.append(int(token, 16) if token.lower().startswith("0x") else int(token))
    return values


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")

    edge_body = extract_block(text, "edgeTable[256]")
    edges = parse_ints(edge_body)
    if len(edges) != 256:
        print(f"edgeTable: expected 256 entries, parsed {len(edges)}")
        return 1

    tri_body = extract_block(text, "triTable[256][16]")
    tris = parse_ints(tri_body)
    if len(tris) != 256 * 16:
        print(f"triTable: expected {256 * 16} entries, parsed {len(tris)}")
        return 1

    lines = [
        "// Generated by Source/RockGen/tools/convert_mc_tables.py from the Unity",
        "// procedural-rock reference (Triangulation.compute), which in turn uses the",
        "// classic Paul Bourke tables: http://paulbourke.net/geometry/polygonise/",
        "",
        "// Do not edit by hand; regenerate with:",
        "//   uv run python Source/RockGen/tools/convert_mc_tables.py",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace RockGen",
        "{",
        "\t// Bit i set means the triangle mesh crosses edge i of the cube cell.",
        "\tstatic constexpr int32_t EDGE_TABLE[256] = {",
    ]
    for i in range(0, 256, 8):
        lines.append("\t\t" + ", ".join(f"0x{e:03x}" for e in edges[i : i + 8]) + ",")
    lines += [
        "\t};",
        "",
        "\t// Up to 5 triangles (15 edge indices) per case, padded with -1.",
        "\tstatic constexpr int32_t TRI_TABLE[256][16] = {",
    ]
    for i in range(256):
        row = tris[i * 16 : i * 16 + 16]
        lines.append("\t\t{ " + ", ".join(f"{v:2d}" for v in row) + " },")
    lines += ["\t};", "} // namespace RockGen", ""]

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(edges)} edges, {256} triangle rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
