@tool
class_name AssetsNodeSettings
extends NodeSettings

@export_group("Assets")

## A list of FlowUserResourceData items representing the assets or resources generated by this node.
@export var assets : Array[ FlowUserResourceData ] = []

func _init():
	super._init()
	resource_name = "Assets Settings"
