#pragma once

// CPU marching-cubes rock generator, a port of the core of Przemyslaw Zaworski's
// "Unity Procedural Rock Generation" (Reference/Unity-Procedural-Rock-Generation/):
//
//   * RockSDF — a base form repeatedly smooth-min'd against hash-seeded bump spheres
//     (ScalarField.compute), which carves the lumpy rock silhouette.
//   * Triplanar FBM displacement along the surface normal, folded into the field before
//     isosurface extraction (proc-rock's "roughness" knob).
//   * Paul Bourke marching cubes (tables in RockMarchingCubesTables.h, generated by
//     tools/convert_mc_tables.py) with gradient normals and per-triangle cube-projection
//     UVs (Triangulation.compute).
//
// The field is evaluated lazily, and every derived quantity is cached so nothing hot
// is recomputed:
//
//   * The hash-seeded bump chain depends only on the seed, so it is precomputed once
//     per generation instead of once per grid sample.
//   * The base SDF fills a Resolution^3 grid together with its central-difference
//     gradient; the noise displacement is only evaluated where the isosurface shell can
//     actually sit (exact, not approximate — outside the shell the density cannot
//     straddle the surface), and is memoised per grid point because up to eight cells
//     share a corner.
//   * Vertex normals and crevice tints come from trilinear interpolation of the cached
//     grid arrays — the CPU analogue of sampling the reference's volume texture.
//
// A 48^3 rock costs ~10^5 noise samples instead of the naive ~3 billion; that is the
// difference between editor-friendly regeneration and not.
//
// proc-rock (Reference/proc-rock/) contributes the form taxonomy — pebble / liquid /
// cube / boulder — reduced here to three base forms (sphere / ellipsoid / rounded box)
// and a ground cut, which is what the CGAL- and libigl-heavy pipeline really boils down
// to for silhouette purposes.

#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <godot_cpp/variant/vector3.hpp>

#include <cstdint>
#include <vector>

namespace RockGen
{
	using godot::Color;
	using godot::Vector2;
	using godot::Vector3;

	/** Base shape the bump blobs and noise displacement carve. */
	enum ERockForm
	{
		/** The reference's unit sphere — a rounded boulder. */
		ROCK_FORM_SPHERE = 0,
		/** Squashed along Y via Flatness — a pebble or river stone. */
		ROCK_FORM_ELLIPSOID = 1,
		/** Rounded box with corner radius from Roundness — a slab with worn edges. */
		ROCK_FORM_ROUNDED_BOX = 2,
	};

	/** Plain snapshot of ProceduralRockParameters. */
	struct RockSpec
	{
		ERockForm Form = ROCK_FORM_SPHERE;
		/** Grid samples per axis; the mesh comes from (Resolution-1)^3 cells. */
		int32_t Resolution = 48;
		/** World size of the generated rock. Generation happens in unit space. */
		float Scale = 2.5f;
		/** Bump-sphere smooth-min iterations (the reference's Steps). */
		int32_t Steps = 20;
		/** Smooth-min blend radius (the reference's Smoothness). */
		float Smoothness = 0.05f;
		/** Seed of the bump hash chain (the reference's Seed). */
		float Seed = 880.0f;
		/** Roughness: triplanar noise amplitude folded into the field. */
		float DisplacementScale = 0.15f;
		/** Roughness frequency (the reference's DisplacementSpread). */
		float DisplacementSpread = 10.0f;
		/** Y squash for ELLIPSOID / Y extent for ROUNDED_BOX, relative to the other axes. */
		float Flatness = 0.7f;
		/** Corner radius of ROUNDED_BOX as a fraction of its half extent. */
		float Roundness = 0.25f;
		/** Flattens the bottom: only the volume above GroundCut (unit space) survives. */
		bool bCutGround = false;
		float GroundCut = -0.3f;

		Color BaseColor = Color(0.45f, 0.46f, 0.47f);
		Color CreviceColor = Color(0.16f, 0.17f, 0.18f);
	};

	/** Growable mesh, one vertex-coloured surface (the same contract as BuildingGen). */
	struct MeshAccumulator
	{
		std::vector<Vector3> Vertices;
		std::vector<Vector3> Normals;
		std::vector<Vector2> UVs;
		std::vector<Color> Colors;
		std::vector<int32_t> Indices;

		int32_t GetTriangleCount() const { return int32_t(Indices.size() / 3); }
	};

	void BuildRock(const RockSpec& Spec, MeshAccumulator& OutMesh);
} // namespace RockGen
